@startuml

class "披萨 \n pizza" as pizza {
    + prepare();
    + bake();
    + cut();
    + box();
}

class chessPizza {
}

class greekPizza {
}

class orderPizza {
}

class orderPizza1 {
}

class orderPizza2 {
}

class SimpleFactory {
}

pizza <|-- chessPizza
pizza <|-- greekPizza

orderPizza --> pizza
orderPizza --> greekPizza
orderPizza --> chessPizza

SimpleFactory <-- orderPizza
SimpleFactory <-- orderPizza1
SimpleFactory <-- orderPizza2

@enduml